version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ${DB_DATA_PATH}:/var/lib/postgresql/data/
    networks:
      - backend
    ports:
      - "5430:5432" # Optional. Проксирование порта для подключения с хоста на 5430 порт
    env_file:
      - .env

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: telegram_scrapper:latest
    volumes:
      - ./app:/app # application
      - ${IMAGES_PATH}:/data/images # images
      - ${ATTACHMENTS_PATH}:/data/attachments # attachments
      - ${TELEGRAM_SESSION_PATH}:/app/session # telegram session
      - ${APP_LOGS_PATH}:/app/logs # logs
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
