version: "3.8"
services:
  db:
    image: postgres:13
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ${DB_DATA_PATH}:/var/lib/postgresql/data/
    networks:
      - backend
    ports:
      - "5430:5432" # Optional. Проксирование порта для подключения с хоста на 5430 порт
    env_file:
      - .env

networks:
  backend:
